[project]
name = "bot"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "aiogram>=3.20.0.post0",
    "bs4>=0.0.2",
    "dotenv>=0.9.9",
    "requests>=2.32.3",
    "youthon>=0.4.3",
    "yt-dlp>=2025.5.22",
]
