name: Build and Push Docker Image

on:
  push:
    branches:
      - master

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/youtube-dl-bot-main:latest

      - name: SSH into server and pull & restart container
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          port: ${{ secrets.SSH_PORT }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            # Обновляем образ
            docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/youtube-dl-bot-main:latest

            # Останавливаем и удаляем старый контейнер
            #docker stop youtube-dl-bot-main || true
            #docker rm youtube-dl-bot-main || true

            # Запускаем новый контейнер
            docker run -d \
              --name youtube-dl-bot-main \
              -e BOT_TOKEN=${{ secrets.BOT_TOKEN }} \
              ${{ secrets.DOCKER_HUB_USERNAME }}/youtube-dl-bot-main:latest